import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { YearProvider } from "@/context/YearContext";
import { YearSelector } from "@/components/YearSelector";
import Link from "next/link";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <YearProvider>
          <div className="min-h-screen flex flex-col">
            <header className="border-b">
              <div className="container mx-auto py-4 flex justify-between items-center">
                <Link href="/" className="text-xl font-bold">F1 Insights</Link>
                <div className="flex items-center gap-4">
                  <Link href="/standings" className="text-sm hover:underline">Standings</Link>
                  <Link href="/schedule" className="text-sm hover:underline">Schedule</Link>
                  <YearSelector />
                </div>
              </div>
            </header>
            <main className="flex-1">
              {children}
            </main>
          </div>
        </YearProvider>
      </body>
    </html>
  );
}
